# SUMMARY: It is a class that contains constants of the code 
#     of each state of Mexico
class MexicoStates(object):
    
    TODOS = '00'
    AGUASCALIENTES = '01'
    BAJA_CALIFORNIA = '02'
    BAJA_CALIFORNIA_SUR = '03'
    CAMPECHE = '04'
    CHIAPAS = '05'
    CHIHUAHUA = '06'
    CIUDAD_DE_MEXICO = '07'
    COAHUILA = '08'
    COLIMA = '09'
    DURANGO = '10'
    GUANAJUATO = '11'
    GUERRERO = '12'
    HIDALGO = '13'
    JALISCO = '14'
    MEXICO = '15'
    MICHOACAN = '16'
    MORELOS = '17'
    NAYARIT = '18'
    NUEVO_LEON = '19'
    OAXACA = '20'
    PUEBLA = '21'
    QUERETARO = '22'
    QUINTANA_ROO = '23'
    SAN_LUIS_POTOSI = '24'
    SINALOA = '25'
    SONORA = '26'
    TABASCO = '27'
    TAMAULIPAS = '28'
    TLAXCALA = '29'
    VERACRUZ = '30'
    YUCATAN = '31'
    ZACATECAS = '32'

# SUMMARY: It is a class that contains constants of the categories of places to 
#     extract data from Inegi
class Places(object):
    
    HOTELES = 'hoteles'
    MOTELES = 'moteles'
    BANCOS = 'bancos'
    TALLERES = 'talleres'
    RESTAURANTES = 'restaurantes'
    SUPERMERCADOS = 'supermercados'
    MERCADOS = 'mercados'
    FARMACIAS = 'farmacias'
    PIZZERIAS = 'pizzeria'
    ESCUELAS_PRIMARIAS = 'primaria'
    ESCUELAS_SECUNDARIAS = 'secundaria'
    ESCUELAS_BACHILLER = 'bachilleratos'
    UNIVERSIDADES = 'universidades'
    CAFETERIAS = 'cafeteria'
    ABARROTES = 'abarrotes'
    VETERINARIAS = 'veterianarias'
    PLAZAS = 'plazas'